# Generated by Django 4.2.11 on 2026-07-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='操作用户ID')),
                ('branch', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='支路编号')),
                ('action_type', models.CharField(choices=[('remote_control', '远程分合闸控制'), ('threshold_update', '修改告警阈值'), ('repair_device', '维修设备'), ('reset_alarm', '告警复位'), ('system_estop', '系统紧急停止')], max_length=30, verbose_name='操作类型')),
                ('is_success', models.BooleanField(default=True, verbose_name='操作是否成功')),
                ('action_detail', models.JSONField(blank=True, null=True, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='浏览器标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '人员操作日志',
                'verbose_name_plural': '人员操作日志',
                'db_table': 'operation_logs',
                'indexes': [models.Index(fields=['user_id'], name='operation_l_user_id_abc9ca_idx'), models.Index(fields=['-created_at'], name='operation_l_created_61eacf_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_id', models.BigIntegerField(verbose_name='关联告警ID')),
                ('user_id', models.BigIntegerField(verbose_name='维修人员ID')),
                ('fault_device', models.CharField(blank=True, max_length=50, null=True, verbose_name='故障设备类型')),
                ('repair_detail', models.TextField(verbose_name='维修措施描述')),
                ('repair_images', models.JSONField(blank=True, null=True, verbose_name='维修图片路径数组')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '故障排查处置日志',
                'verbose_name_plural': '故障排查处置日志',
                'db_table': 'maintenance_logs',
                'indexes': [models.Index(fields=['alarm_id'], name='maintenance_alarm_i_2e8e45_idx'), models.Index(fields=['user_id'], name='maintenance_user_id_807afb_idx')],
            },
        ),
    ]
