# Generated by Django 4.2.11 on 2026-07-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='告警触发时间')),
                ('branch', models.PositiveSmallIntegerField(verbose_name='支路编号')),
                ('alarm_level', models.CharField(choices=[('hot_spot', '热斑告警'), ('over_temp', '温度过载告警'), ('offline', '设备离线告警')], max_length=20, verbose_name='告警分类')),
                ('warning_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='严重等级(1/2/3)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警描述')),
                ('image_path', models.CharField(max_length=500, verbose_name='红外热成像原图路径')),
                ('annotated_image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='AI标注图路径')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最高温度(℃)')),
                ('temp_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='局部温差(℃)')),
                ('area_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='热斑面积占比(%)')),
                ('threshold_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='触发温度阈值(℃)')),
                ('threshold_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='触发面积阈值(%)')),
                ('auto_trip', models.BooleanField(default=True, verbose_name='是否自动跳闸')),
                ('action', models.CharField(blank=True, choices=[('trip', '跳闸'), ('reset', '复位'), ('none', '无动作')], max_length=10, null=True, verbose_name='执行动作')),
                ('resolution_status', models.CharField(choices=[('pending', '未处理'), ('resolved', '已处理'), ('recovering', '恢复中')], default='pending', max_length=20, verbose_name='处置状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处置完成时间')),
                ('resolved_by', models.BigIntegerField(blank=True, null=True, verbose_name='处置人ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'db_table': 'alarm_logs',
                'indexes': [models.Index(fields=['timestamp'], name='alarm_logs_timesta_d4a42c_idx'), models.Index(fields=['branch'], name='alarm_logs_branch_40e233_idx'), models.Index(fields=['alarm_level'], name='alarm_logs_alarm_l_f2185a_idx'), models.Index(fields=['resolution_status'], name='alarm_logs_resolut_1aa6c8_idx'), models.Index(fields=['branch', 'timestamp'], name='alarm_logs_branch_0a533a_idx'), models.Index(fields=['resolution_status', 'timestamp'], name='alarm_logs_resolut_1d2462_idx')],
            },
        ),
    ]
