# Generated by Django 4.2.11 on 2026-07-04 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_maintenancelog_maintenance_created_793f8c_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="配置键名"
                    ),
                ),
                (
                    "config_value",
                    models.CharField(max_length=255, verbose_name="配置值"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="配置说明"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="最后更新人ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_config",
            },
        ),
        migrations.RenameIndex(
            model_name="alarmlog",
            new_name="idx_alarm_timestamp",
            old_name="alarm_logs_timesta_d4a42c_idx",
        ),
        migrations.RenameIndex(
            model_name="alarmlog",
            new_name="idx_alarm_branch",
            old_name="alarm_logs_branch_40e233_idx",
        ),
        migrations.RenameIndex(
            model_name="alarmlog",
            new_name="idx_alarm_level",
            old_name="alarm_logs_alarm_l_f2185a_idx",
        ),
        migrations.RenameIndex(
            model_name="alarmlog",
            new_name="idx_alarm_resolution_status",
            old_name="alarm_logs_resolut_1aa6c8_idx",
        ),
        migrations.RenameIndex(
            model_name="alarmlog",
            new_name="idx_alarm_branch_timestamp",
            old_name="alarm_logs_branch_0a533a_idx",
        ),
        migrations.RenameIndex(
            model_name="alarmlog",
            new_name="idx_alarm_status_timestamp",
            old_name="alarm_logs_resolut_1d2462_idx",
        ),
        migrations.RenameIndex(
            model_name="maintenancelog",
            new_name="idx_mt_alarm_id",
            old_name="maintenance_alarm_i_2e8e45_idx",
        ),
        migrations.RenameIndex(
            model_name="maintenancelog",
            new_name="idx_mt_user_id",
            old_name="maintenance_user_id_807afb_idx",
        ),
        migrations.RenameIndex(
            model_name="maintenancelog",
            new_name="idx_mt_created_at",
            old_name="maintenance_created_793f8c_idx",
        ),
        migrations.RenameIndex(
            model_name="maintenancelog",
            new_name="idx_mt_alarm_created",
            old_name="maintenance_alarm_i_042d92_idx",
        ),
        migrations.RenameIndex(
            model_name="operationlog",
            new_name="idx_op_user_id",
            old_name="operation_l_user_id_abc9ca_idx",
        ),
        migrations.RenameIndex(
            model_name="operationlog",
            new_name="idx_op_created_at",
            old_name="operation_l_created_61eacf_idx",
        ),
        migrations.RenameIndex(
            model_name="operationlog",
            new_name="idx_op_user_created",
            old_name="operation_l_user_id_0c8567_idx",
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="branch",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="故障支路编号"
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="fault_date",
            field=models.DateField(
                default=datetime.date(2026, 1, 1), verbose_name="故障日期"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="fault_time",
            field=models.TimeField(
                default=datetime.time(0, 0), verbose_name="故障时间"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="annotated_image_path",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="带AI标注的告警图片路径",
            ),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="area_ratio",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="热斑面积占比（%）"
            ),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="处置完成/恢复时间"
            ),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="temp_difference",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="局部温差（℃）",
            ),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="触发告警时的最高温度（℃）"
            ),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="threshold_area",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="触发时的面积阈值（%）"
            ),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="threshold_temp",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="触发时的温度阈值（℃）"
            ),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="timestamp",
            field=models.DateTimeField(verbose_name="告警触发时间"),
        ),
        migrations.AlterField(
            model_name="alarmlog",
            name="warning_level",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="严重等级（1/2/3）"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="alarm_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="关联的告警记录ID"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="处置记录创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="repair_detail",
            field=models.TextField(verbose_name="维修措施详细描述"),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="repair_images",
            field=models.JSONField(
                blank=True, null=True, verbose_name="维修现场图片路径数组"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action_detail",
            field=models.JSONField(
                blank=True, null=True, verbose_name="操作详情（JSON格式）"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="branch",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="操作的支路编号"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="操作来源IP地址"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="user_agent",
            field=models.TextField(
                blank=True, null=True, verbose_name="浏览器/客户端标识"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancelog",
            index=models.Index(fields=["branch"], name="idx_mt_branch"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["branch"], name="idx_op_branch"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["action_type"], name="idx_op_action_type"),
        ),
        migrations.AddConstraint(
            model_name="alarmlog",
            constraint=models.CheckConstraint(
                check=models.Q(("branch__gte", 1), ("branch__lte", 4)),
                name="chk_alarm_logs_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarmlog",
            constraint=models.CheckConstraint(
                check=models.Q(("temperature__gte", -20), ("temperature__lte", 150)),
                name="chk_alarm_logs_temperature",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarmlog",
            constraint=models.CheckConstraint(
                check=models.Q(("area_ratio__gte", 0), ("area_ratio__lte", 100)),
                name="chk_alarm_logs_area_ratio",
            ),
        ),
        migrations.AddConstraint(
            model_name="alarmlog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("warning_level__in", [1, 2, 3]),
                    ("warning_level__isnull", True),
                    _connector="OR",
                ),
                name="chk_alarm_logs_warning_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancelog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("branch__gte", 1), ("branch__lte", 4)),
                    ("branch__isnull", True),
                    _connector="OR",
                ),
                name="chk_maintenance_logs_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationlog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("branch__gte", 1), ("branch__lte", 4)),
                    ("branch__isnull", True),
                    _connector="OR",
                ),
                name="chk_operation_logs_branch",
            ),
        ),
    ]
