# Generated by Django 4.2 on 2026-07-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_maintenancelog_fault_date_fault_time'),
        ('logs', '0004_systemconfig_and_more'),
    ]

    operations = [
    ]
