# Generated by Django 4.2.11 on 2026-07-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_merge_20260705_1844"),
        ("logs", "0005_merge_20260705_1855"),
    ]

    operations = []
