# Generated by Django 4.2.11 on 2026-07-07 02:43

from django.db import migrations, models


def migrate_is_success_to_maintenance_status(apps, schema_editor):
    """
    将旧数据迁移：is_success=True → 'maintained', is_success=False → 'unmaintained'
    """
    OperationLog = apps.get_model('logs', 'OperationLog')
    OperationLog.objects.filter(is_success=True).update(maintenance_status='maintained')
    OperationLog.objects.filter(is_success=False).update(maintenance_status='unmaintained')


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0006_merge_20260706_1509"),
    ]

    operations = [
        # 1. 先添加 maintenance_status（带默认值）
        migrations.AddField(
            model_name="operationlog",
            name="maintenance_status",
            field=models.CharField(
                choices=[
                    ("maintained", "已维护"),
                    ("maintaining", "维护中"),
                    ("unmaintained", "未维护"),
                ],
                default="unmaintained",
                max_length=20,
                verbose_name="维护状态",
            ),
        ),
        # 2. 数据迁移：is_success → maintenance_status
        migrations.RunPython(
            migrate_is_success_to_maintenance_status,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3. 删除 is_success
        migrations.RemoveField(
            model_name="operationlog",
            name="is_success",
        ),
        # 4. MaintenanceLog 新增 remark
        migrations.AddField(
            model_name="maintenancelog",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注信息"),
        ),
    ]
