# Generated by Django 4.2 on 2026-07-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_merge_20260706_1637'),
        ('logs', '0007_remove_operationlog_is_success_maintenancelog_remark_and_more'),
    ]

    operations = [
    ]
