# Generated by Django 4.2.11 on 2026-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmrecord",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2,
                help_text="触发告警时的热斑区域最高温度",
                max_digits=5,
                verbose_name="最高温度（℃）",
            ),
        ),
        migrations.AlterField(
            model_name="alarmrecord",
            name="threshold_area",
            field=models.DecimalField(
                decimal_places=2,
                help_text="告警触发时的面积阈值快照",
                max_digits=5,
                verbose_name="面积阈值（%）",
            ),
        ),
        migrations.AlterField(
            model_name="alarmrecord",
            name="threshold_temp",
            field=models.DecimalField(
                decimal_places=2,
                help_text="告警触发时的温度阈值快照",
                max_digits=5,
                verbose_name="温度阈值（℃）",
            ),
        ),
        migrations.AlterField(
            model_name="alarmrecord",
            name="warning_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "一级告警"), (2, "二级告警"), (3, "三级告警")],
                help_text="1=一级（最严重）, 2=二级, 3=三级",
                null=True,
                verbose_name="严重等级",
            ),
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="area_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="热斑区域面积占光伏板总面积的百分比",
                max_digits=5,
                verbose_name="热斑面积占比（%）",
            ),
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="avg_temp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="该支路在当前采集周期内的平均温度",
                max_digits=5,
                null=True,
                verbose_name="平均温度（℃）",
            ),
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="数据入库时间", verbose_name="记录创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="hotspot_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="当前采集周期内检测到的热斑个数",
                verbose_name="热斑数量",
            ),
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="max_temp",
            field=models.DecimalField(
                decimal_places=2,
                help_text="该支路在当前采集周期内的最高温度",
                max_digits=5,
                verbose_name="最高温度（℃）",
            ),
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="min_temp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="该支路在当前采集周期内的最低温度",
                max_digits=5,
                null=True,
                verbose_name="最低温度（℃）",
            ),
        ),
    ]
