# Generated by Django 5.2.15 on 2026-07-03 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='设备ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('meter', '电表'), ('switch', '开关'), ('sensor', '传感器'), ('controller', '控制器')], max_length=30, verbose_name='设备类型')),
                ('branch', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='支路编号')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('fault', '故障'), ('maintenance', '维护中')], default='offline', max_length=20, verbose_name='设备状态')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='安装位置')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'devices',
                'indexes': [models.Index(fields=['device_id'], name='devices_device__c4b5e4_idx'), models.Index(fields=['branch'], name='devices_branch_643290_idx'), models.Index(fields=['status'], name='devices_status_9f14cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(choices=[('switch_on', '合闸'), ('switch_off', '分闸'), ('reset', '复位'), ('calibrate', '校准'), ('configure', '配置')], max_length=30, verbose_name='控制类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('executed', '已执行'), ('failed', '执行失败'), ('timeout', '超时')], default='pending', max_length=20, verbose_name='执行状态')),
                ('control_params', models.JSONField(blank=True, null=True, verbose_name='控制参数')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='响应数据')),
                ('operator_id', models.BigIntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_records', to='devices.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备控制记录',
                'verbose_name_plural': '设备控制记录',
                'db_table': 'device_controls',
                'indexes': [models.Index(fields=['device'], name='device_cont_device__5c51e6_idx'), models.Index(fields=['status'], name='device_cont_status_76e829_idx'), models.Index(fields=['-created_at'], name='device_cont_created_9c8e0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='电压(V)')),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='电流(A)')),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='功率(W)')),
                ('energy', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='电能(kWh)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='温度(℃)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='湿度(%)')),
                ('power_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='功率因数')),
                ('frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='频率(Hz)')),
                ('data_time', models.DateTimeField(verbose_name='数据时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='devices.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备数据',
                'verbose_name_plural': '设备数据',
                'db_table': 'device_data',
                'indexes': [models.Index(fields=['device'], name='device_data_device__d26218_idx'), models.Index(fields=['-data_time'], name='device_data_data_ti_25ed2a_idx')],
            },
        ),
    ]
