# Generated by Django 4.2.20 on 2026-07-03 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(choices=[(1, '支路1'), (2, '支路2'), (3, '支路3'), (4, '支路4')], unique=True, verbose_name='支路编号')),
                ('temperature', models.FloatField(default=0.0, verbose_name='当前最高温度(℃)')),
                ('area_ratio', models.FloatField(default=0.0, verbose_name='热斑面积占比(%)')),
                ('breaker_status', models.CharField(choices=[('closed', '合闸'), ('open', '分闸')], default='closed', max_length=16, verbose_name='断路器状态')),
                ('alarm_status', models.CharField(choices=[('normal', '正常'), ('alarm', '告警')], default='normal', max_length=16, verbose_name='告警状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '支路实时状态',
                'verbose_name_plural': '支路实时状态',
                'db_table': 'monitor_branch_status',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(choices=[('temperature_threshold', '温度告警阈值(℃)'), ('area_ratio_threshold', '面积告警阈值(%)'), ('mqtt_broker_host', 'MQTT Broker地址'), ('mqtt_broker_port', 'MQTT Broker端口'), ('data_retention_days', '数据保留天数')], max_length=64, unique=True, verbose_name='配置键')),
                ('config_value', models.CharField(max_length=256, verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='配置说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'monitor_system_config',
            },
        ),
        migrations.CreateModel(
            name='ThermalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='采集时间')),
                ('device_id', models.CharField(default='raspberrypi-01', max_length=128, verbose_name='设备标识')),
                ('image_path', models.CharField(max_length=512, verbose_name='原始图像路径')),
                ('annotated_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='标注图像路径')),
                ('width', models.IntegerField(default=256, verbose_name='图像宽度')),
                ('height', models.IntegerField(default=192, verbose_name='图像高度')),
                ('hotspots', models.JSONField(blank=True, default=list, verbose_name='热斑坐标信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '红外热像图',
                'verbose_name_plural': '红外热像图',
                'db_table': 'monitor_thermal_image',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='monitor_the_timesta_a8482b_idx'), models.Index(fields=['device_id', 'timestamp'], name='monitor_the_device__7a93bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemperatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='支路编号')),
                ('timestamp', models.DateTimeField(verbose_name='记录时间点')),
                ('max_temp', models.FloatField(verbose_name='最高温度(℃)')),
                ('avg_temp', models.FloatField(verbose_name='平均温度(℃)')),
                ('area_ratio', models.FloatField(default=0.0, verbose_name='热斑面积占比(%)')),
                ('sample_count', models.IntegerField(default=1, verbose_name='采样次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '温度历史记录',
                'verbose_name_plural': '温度历史记录',
                'db_table': 'monitor_temperature_record',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['branch', 'timestamp'], name='monitor_tem_branch_0dad05_idx'), models.Index(fields=['timestamp'], name='monitor_tem_timesta_11af0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('thermal_camera', '热像仪'), ('mqtt', 'MQTT服务'), ('raspberrypi', '树莓派')], max_length=32, verbose_name='设备类型')),
                ('device_id', models.CharField(default='default', max_length=128, verbose_name='设备标识')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=16, verbose_name='在线状态')),
                ('extra_info', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最后在线时间')),
            ],
            options={
                'verbose_name': '设备状态',
                'verbose_name_plural': '设备状态',
                'db_table': 'monitor_device_status',
                'unique_together': {('device_type', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='AlarmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='支路编号')),
                ('alarm_type', models.CharField(choices=[('hot_spot', '热斑告警'), ('over_temp', '温度过载告警'), ('offline', '设备离线告警')], max_length=32, verbose_name='告警类型')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='触发温度(℃)')),
                ('area_ratio', models.FloatField(blank=True, null=True, verbose_name='热斑面积占比(%)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('recovering', '恢复中'), ('resolved', '已处理')], default='pending', max_length=32, verbose_name='处置状态')),
                ('image_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='告警截图路径')),
                ('description', models.TextField(blank=True, null=True, verbose_name='告警描述')),
                ('auto_trip', models.BooleanField(default=False, verbose_name='是否自动分闸')),
                ('timestamp', models.DateTimeField(verbose_name='告警时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'monitor_alarm_record',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['branch', 'timestamp'], name='monitor_ala_branch_b67860_idx'), models.Index(fields=['alarm_type'], name='monitor_ala_alarm_t_1e3277_idx'), models.Index(fields=['status'], name='monitor_ala_status_6b879d_idx'), models.Index(fields=['timestamp'], name='monitor_ala_timesta_f3223f_idx')],
            },
        ),
    ]
