# Generated by Django 4.2.30 on 2026-07-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='UNet', max_length=64, verbose_name='模型名称')),
                ('model_version', models.CharField(default='1.0.0', max_length=32, verbose_name='模型版本')),
                ('framework', models.CharField(default='PyTorch → ONNX', max_length=32, verbose_name='训练/推理框架')),
                ('architecture', models.CharField(default='UNet', max_length=64, verbose_name='网络架构')),
                ('input_size', models.CharField(default='256×192', max_length=32, verbose_name='输入尺寸')),
                ('base_channels', models.IntegerField(default=32, verbose_name='基础通道数')),
                ('dataset_size', models.IntegerField(default=2000, verbose_name='训练样本数')),
                ('epochs', models.IntegerField(default=100, verbose_name='训练轮数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='补充说明')),
                ('deployed_at', models.DateTimeField(auto_now_add=True, verbose_name='部署时间')),
            ],
            options={
                'verbose_name': 'AI 模型信息',
                'verbose_name_plural': 'AI 模型信息',
                'db_table': 'ai_model_info',
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iou', models.FloatField(verbose_name='IoU (交并比)')),
                ('dice', models.FloatField(verbose_name='Dice 系数')),
                ('pixel_accuracy', models.FloatField(verbose_name='像素准确率')),
                ('precision', models.FloatField(verbose_name='精确率 (Precision)')),
                ('recall', models.FloatField(verbose_name='召回率 (Recall)')),
                ('inference_latency_ms', models.FloatField(verbose_name='推理延迟 (ms)')),
                ('fps', models.FloatField(verbose_name='FPS (每秒帧数)')),
                ('eval_dataset_size', models.IntegerField(default=200, verbose_name='验证集样本数')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': 'AI 性能指标',
                'verbose_name_plural': 'AI 性能指标',
                'db_table': 'ai_performance_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
