# Generated by Django 4.2.11 on 2026-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_alarmlog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="maintenancelog",
            index=models.Index(
                fields=["-created_at"], name="maintenance_created_793f8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancelog",
            index=models.Index(
                fields=["alarm_id", "created_at"], name="maintenance_alarm_i_042d92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["user_id", "created_at"], name="operation_l_user_id_0c8567_idx"
            ),
        ),
    ]
